name: Create JSON
run-name: Parse RSS into JSON
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-json:
    runs-on: ubuntu-latest
    steps:
      # Setup environment
      - name: Check out repository
        uses: actions/checkout@v4
      - run: |
          curl -sSL https://bit.ly/install-xq | sudo bash
      - run: |
          cd ${{ gitea.workspace }}
      - run: mkdir -p json

      # Fetch the RSS feed, strip the first 10 items, and convert to JSON
      - run: |
          curl -s https://enterprise.github.com/releases.rss \
          | xq -j | jq '.rss.channel.item[:10]' > json/releases.json
      - run: |
          curl -s https://enterprise.github.com/releases.rss \
          | xq -j | jq -r '.rss.channel.item[0].title' > latest

      # Add the new file to the repository and commit it
      - name: Commit and push changes
        run: |
          git config --global user.name "gitea-actions[bot]"
          git config --global user.email "gitea-actions[bot]@users.noreply.gitea.jrdn.dev"
          git add json/releases.json
          git add latest
          git commit -m "Update releases and latest"
          git push origin master